In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras import Sequential
from tensorflow.keras.losses import MeanSquaredError, BinaryCrossentropy
from tensorflow.keras.activations import sigmoid
import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)

In [ ]:
X_train = np.array([[1, 2], [1.5, 0.5], [0.5, 2.5]])
# NDArray.shape for the matrix returns (row_count, col_count)
# The amount of rows is X_train.shape[0], the amount of cols is X_train.shape[1]
# I assume that amount of rows is the size of a training set, i.e. how many records we do have
# The amount of columns is how many variables per one experiment we have (for house prediction - floors count, bathrooms count, square space etc)

sample_size = X_train.shape[1]
# How may neurons do we want in a layer
amount_of_neurons = 3
W = np.ones((amount_of_neurons, sample_size))
B = np.zeros((amount_of_neurons, 1))

# Since I want to use matrix multiplication for W and X_train, I have to transpose X_train
# Because W matrix row contains weights for a single learning sample and during multiplication
# in is multiplied with the first column of second matrix (X_train), so we have to put values of x
# for every sample to be in a same row, not in a same column

# The result of W * X_train.T is the matrix where:
# - each column contains data for single training sample
#   the first element of the column is the first neuron data, the second is for second neuron etc
# - first column is data for every neuron for the first sample, second column - second sample etc
# _______________________________________________________________________________________________________________________
# | W_fist_neuron · X_first_sample      |   W_fist_neuron · X_second_sample     |   W_fist_neuron · X_third_sample      |
# | W_second_neuron · X_first_sample    |   W_second_neuron · X_second_sample   |   W_second_neuron · X_third_sample    |
# | W_third_neuron · X_first_sample     |   W_third_neuron · X_second_sample    |   W_third_neuron · X_third_sample     |
# ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾

result = np.matmul(W, X_train.T) + B
print(W)
print(X_train.T)
print(B)
result

In [37]:
def sigmoid(z):
    z = np.clip(z, -500, 500 ) #protect against overflow
    return 1 / (1 + np.exp(-z))

X = np.array([[-2, 2], [0, 1]])
sigmoid(X)

array([[0.11920292, 0.88079708],
       [0.5       , 0.73105858]])

In [38]:
W_1 = np.array([
    [-8.93, -0.1 ],
    [0.29, -7.32],
    [12.9, 10.81]
])

X_1 = np.array([
    [-0.47, -0.47 ],
    [0.42, 3.16]
])

B_1 = np.array( [-9.82, -9.28,  0.96] )[:, np.newaxis]

print(W_1)
print(X_1)
print(B_1)

A_1 = np.matmul(W_1, X_1) + B_1
print('Before sigmoid')
print(A_1)
print('After sigmoid')
A_1 = sigmoid(A_1)
print(A_1)


[[-8.93 -0.1 ]
 [ 0.29 -7.32]
 [12.9  10.81]]
[[-0.47 -0.47]
 [ 0.42  3.16]]
[[-9.82]
 [-9.28]
 [ 0.96]]
Before sigmoid
[[ -5.6649  -5.9389]
 [-12.4907 -32.5475]
 [ -0.5628  29.0566]]
After sigmoid
[[3.45352613e-03 2.62800188e-03]
 [3.76145856e-06 7.32487723e-15]
 [3.62899842e-01 1.00000000e+00]]


In [39]:
W_2 = np.array([
    [-31.18, -27.59, -32.56]
])

B_2 = np.array([[15.41]])
A_2 = np.matmul(W_2, A_1) + B_2
sigmoid(A_2)

array([[9.70292454e-01, 3.28294082e-08]])